name: Deploy 9103H gh-pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Dev Repo
        uses: actions/checkout@v3

      - name: Deploy GH pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.PUSH_TOKEN }}
          external_repository: 9103H/9103H.github.io
          publish_branch: gh-pages
          publish_dir: ./
          enable_jekyll: true
